name: etech_store_admin
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  adaptive_theme: ^3.6.0
  cloud_firestore: ^4.17.2
  connectivity_plus: ^6.0.3
  firebase_auth: ^4.19.4
  get: ^4.6.6
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  lottie: ^3.1.0
  pinput: ^4.0.0
  flutter_lints: ^3.0.2
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.9
  internet_connection_checker_plus: ^2.3.0
  responsive_builder: ^0.7.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  month_picker_dialog: ^4.0.0
  excel: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
